---
name: 'Environment Health Check & Teardown'
description: 'ðŸ›¡ï¸ Ensure infrastructure stability before tests and perform surgical cleanup after execution.'
branding:
  icon: 'shield'
  color: 'green'
inputs:
  task:
    description: 'Task to perform: "setup" (pre-flight + startup) or "teardown" (cleanup)'
    required: true
    default: 'setup'
  start-services-command:
    description: 'Optional command to start services during setup'
    required: false
  health-check-urls:
    description: 'URLs to verify after starting services'
    required: false
  db-path:
    description: 'Path to SQLite database to verify integrity'
    required: false
  ports-to-clean:
    description: 'Space-separated ports to clear before setup (e.g., 3000 3001)'
    required: false
    default: '3000 3001'

runs:
  using: 'composite'
  steps:
    - name: ðŸ” Pre-flight Cleanup
      if: ${{ inputs.task == 'setup' }}
      shell: bash
      run: |
        echo "ðŸ§¹ Performing pre-flight cleanup..."
        for port in ${{ inputs.ports-to-clean }}; do
          echo "Checking port $port..."
          PID=$(lsof -t -i:$port 2>/dev/null || true)
          if [ ! -z "$PID" ]; then
            echo "Killing process $PID on port $port"
            kill -9 $PID || true
          fi
        done
        # Generic cleanup of common test processes
        pkill -f "node" || true
        pkill -f "python" || true
          
    - name: ðŸ—„ï¸ Database Integrity Check
      if: ${{ inputs.task == 'setup' && inputs.db-path != '' }}
      shell: bash
      run: |
        if [ -f "${{ inputs.db-path }}" ]; then
          echo "ðŸ” Checking SQLite integrity for ${{ inputs.db-path }}..."
          sqlite3 "${{ inputs.db-path }}" "PRAGMA integrity_check;" | grep -q "ok" || (
            echo "::error::Database corrupted at ${{ inputs.db-path }}. Attempting to recover by deletion..."
            rm -f "${{ inputs.db-path }}"
          )
        else
          echo "Note: Database file not found at ${{ inputs.db-path }}, skipping integrity check."
        fi

    - name: âš™ï¸ Setup Services
      if: ${{ inputs.task == 'setup' && inputs.start-services-command != '' }}
      uses: carlos-camara/qa-hub-actions/setup-services@main
      with:
        start-services-command: ${{ inputs.start-services-command }}
        health-check-urls: ${{ inputs.health-check-urls }}

    - name: ðŸ›‘ Teardown Environment
      if: ${{ inputs.task == 'teardown' }}
      shell: bash
      run: |
        echo "ðŸ§¼ Performing environment teardown..."
        for port in ${{ inputs.ports-to-clean }}; do
          PID=$(lsof -t -i:$port 2>/dev/null || true)
          if [ ! -z "$PID" ]; then
            echo "Cleaning up process $PID on port $port"
            kill -9 $PID || true
          fi
        done
        # Clean up temp files
        find . -name "*.log" -type f -delete || true
        echo "Environment cleaned."
