---
name: 'Lint Codebase Standard'
description: 'Runs Super-Linter with standardized rules for QA Hub projects.'
branding:
  icon: 'shield'
  color: 'green'
inputs:
  github-token:
    description: 'GitHub Token for posting status checks.'
    required: true
  default-branch:
    description: 'Default branch for comparison (e.g. main).'
    required: false
    default: 'main'
  validate-all:
    description: 'Validate entire codebase (true) or just changes (false).'
    required: false
    default: 'false'
  validate-python:
    description: 'Lint Python files?'
    required: false
    default: 'true'
  validate-yaml:
    description: 'Lint YAML files?'
    required: false
    default: 'true'
  validate-markdown:
    description: 'Lint Markdown files?'
    required: false
    default: 'true'
  validate-actions:
    description: 'Lint GitHub Actions?'
    required: false
    default: 'true'
  validate-ts:
    description: 'Lint TypeScript/JS?'
    required: false
    default: 'true'
  filter-regex-exclude:
    description: 'Regex for ignored paths.'
    required: false
    default: '(\.venv/|_pycache_/|reports/|\.git/|\.pytest_cache/|node_modules/|dist/|coverage/)'

runs:
  using: "composite"
  steps:
    - name: 🔍 Super-Linter
      uses: super-linter/super-linter@v7
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
        VALIDATE_ALL_CODEBASE: ${{ inputs.validate-all }}
        VALIDATE_PYTHON: ${{ inputs.validate-python }}
        VALIDATE_YAML: ${{ inputs.validate-yaml }}
        VALIDATE_MARKDOWN: ${{ inputs.validate-markdown }}
        VALIDATE_GITHUB_ACTIONS: ${{ inputs.validate-actions }}
        VALIDATE_TYPESCRIPT_ES: ${{ inputs.validate-ts }}
        VALIDATE_JAVASCRIPT_ES: ${{ inputs.validate-ts }}
        VALIDATE_TSX: ${{ inputs.validate-ts }}
        FILTER_REGEX_EXCLUDE: ${{ inputs.filter-regex-exclude }}
        # Force ESLint Flat Config (v9+ Compatibility)
        ESLINT_USE_FLAT_CONFIG: "true"
        JAVASCRIPT_ES_ESLINT_CONFIG_FILE: "eslint.config.mjs"
        TYPESCRIPT_ES_ESLINT_CONFIG_FILE: "eslint.config.mjs"

    - name: ✅ Mark Linting as Passed
      if: success() && github.event_name == 'pull_request'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        echo "Linting passed! Updating PR checklist..."
        CURRENT_BODY=$(gh pr view "$PR_NUMBER" --json body --template '{{.body}}')
        
        cat << 'EOF' > patch_lint.py
        import sys, re, os
        
        try:
            body = os.environ.get('CURRENT_BODY', '')
            
            # Regex for: - [ ] 🧹 **Linting**
            # Handles variable whitespace
            pattern = r'-\s*\[\s*\]\s*🧹\s*\*\*Linting\*\*'
            
            if re.search(pattern, body):
                print("Linting checkbox found. Marking as checked...", file=sys.stderr)
                replacement = '- [x] 🧹 **Linting**'
                new_body = re.sub(pattern, replacement, body)
                print(new_body)
            else:
                print("Linting checkbox not found or already checked.", file=sys.stderr)
                sys.exit(0) # Exit success but don't print body to avoid processing
                
        except Exception as e:
            print(f"Error patching PR: {e}", file=sys.stderr)
            sys.exit(1)
        EOF
        
        # Capture logic
        export CURRENT_BODY
        NEW_BODY=$(python patch_lint.py)
        
        if [ -n "$NEW_BODY" ]; then
            echo "$NEW_BODY" > pr_body.md
            gh pr edit "$PR_NUMBER" --body-file pr_body.md
            echo "✅ PR checklist updated."
        else
            echo "⚠️ No changes to apply."
        fi
