---
name: 'Deploy Reports to S3'
description: 'Downloads test artifacts and uploads them to AWS S3 with proper project structure.'

inputs:
  project-name:
    description: 'Project identifier for S3 prefix (e.g., "dashboard", "api-tests")'
    required: true
  s3-bucket:
    description: 'AWS S3 bucket name'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'
  github-token:
    description: 'GitHub token with actions:read permissions'
    required: true
    default: ${{ github.token }}
  run-id:
    description: 'GitHub Workflow Run ID to download artifacts from'
    required: true
  upload-reports:
    description: 'Upload test reports?'
    required: false
    default: 'true'
  upload-screenshots:
    description: 'Upload GUI screenshots?'
    required: false
    default: 'true'
  upload-perf:
    description: 'Upload performance reports?'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: 📥 Download Test Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: '*'
        path: temp_s3
        github-token: ${{ inputs.github-token }}
        run-id: ${{ inputs.run-id }}
        merge-multiple: false

    - name: ☁️ Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: 📤 Upload to S3
      shell: bash
      run: |
        echo "🔍 Debugging S3 Connectivity..."
        aws s3 ls || echo "⚠️ Cannot list buckets (Permission/Auth Issue)"
        
        echo "🚀 Uploading reports to S3..."
        PROJECT="${{ inputs.project-name }}"
        BUCKET="${{ inputs.s3-bucket }}"
        echo "DEBUG: Target Bucket is [${BUCKET}]"
        
        # Helper to sync without deletion
        sync_to_s3() {
          local src=$1
          local dest=$2
          local label=$3
          if [ -d "$src" ]; then
            echo "📦 Uploading ${label}..."
            aws s3 sync "$src" "s3://${BUCKET}/${PROJECT}/${dest}/" \
              --exclude "*.gitkeep" || echo "⚠️ Failed to upload ${label}"
          else
            echo "⏭️ Skipping ${label}: Directory not found ($src)"
          fi
        }

        if [ "${{ inputs.upload-reports }}" == "true" ]; then
          sync_to_s3 "temp_s3/test-reports" "reports/test_run" "Test Reports"
        fi
        
        if [ "${{ inputs.upload-screenshots }}" == "true" ]; then
          sync_to_s3 "temp_s3/gui-screenshots" "reports/screenshots" "GUI Screenshots"
        fi
        
        if [ "${{ inputs.upload-perf }}" == "true" ]; then
          sync_to_s3 "temp_s3/performance-reports" "reports/performance_run" "Performance Reports"
        fi
        
        echo "✅ S3 upload sequence complete!"
