name: 🎨 Promote Visual Baselines

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID with valid screenshots to promote'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Update Baselines
        uses: carlos-camara/qa-hub-actions/visual-regression-manager@main
        with:
          run-id: ${{ inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          driver-type: 'chrome'
