name: 🐛 Bug Report
description: File a report to help us improve.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce it?
      description: Provide a minimal workflow or repository if possible.
    validations:
      required: true
  - type: dropdown
    id: action
    attributes:
      label: Which action is affected?
      options:
        - setup-environment
        - run-tests
        - collect-and-publish
        - other
    validations:
      required: true
