name: 'PR Summarizer'
description: '🤖 Automatically summarize PR changes following your pull_request_template.md structure.'
branding:
  icon: 'message-square'
  color: 'purple'
inputs:
  github-token:
    description: 'GitHub token for PR description/comment updates'
    required: true
  domain-mapping:
    description: 'JSON string mapping file patterns to domains'
    required: false
  target:
    description: 'Where to post the summary (description or comment)'
    required: false
    default: 'description'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Summarizer
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DOMAIN_MAPPING: ${{ inputs.domain-mapping }}
        TARGET: ${{ inputs.target }}
      run: |
        python ${{ github.action_path }}/summarize.py
