name: 'Publish Test Results'
description: '📊 Parse JUnit results and post a professional summary comment to the PR.'
branding:
  icon: 'message-square'
  color: 'blue'
inputs:
  reports-path:
    description: 'Path to JUnit XML reports'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
  title:
    description: 'Title for the test report'
    required: false
    default: 'Test Execution Summary'
  target:
    description: 'Where to publish: comment or description'
    required: false
    default: 'description'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Generate Summary Markdown
      shell: bash
      run: python ${{ github.action_path }}/reporter.py "${{ inputs.reports-path }}"

    - name: Publish Results
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        TARGET: ${{ inputs.target }}
      run: |
        if [ -z "$PR_NUMBER" ]; then
          echo "Not a PR, appending to step summary."
          cat test_summary.md >> $GITHUB_STEP_SUMMARY
          exit 0
        fi

        if [ "$TARGET" == "description" ]; then
          echo "Injecting results into PR description..."
          CURRENT_BODY=$(gh pr view "$PR_NUMBER" --json body --template '{{.body}}')
          
          # Check if anchor exists
          if echo "$CURRENT_BODY" | grep -q "## 🚦 Test Results"; then
            # Replace the section up to the next heading or end of file
            # Export body to env for python script
            export CURRENT_BODY
            
            # Using python to safe multiline replacement
            NEW_BODY=$(python -c "
            import sys, re, os
            body = os.environ['CURRENT_BODY']
            summary = open('test_summary.md').read()
            outcome = open('test_outcome.txt').read().strip()
            
            # Inject Summary
            anchor = '## 🚦 Test Results'
            pattern = rf'({re.escape(anchor)})(.*?)(\n## |$)'
            
            if anchor in body:
                body = re.sub(pattern, rf'\1\n\n' + summary.replace('\\', '\\\\').replace('$', '\\$') + r'\3', body, flags=re.DOTALL)
            else:
                body = body + '\n\n' + anchor + '\n\n' + summary
            
            # Auto-check box if success
            if outcome == 'SUCCESS':
                body = body.replace('- [ ] 🧪 **Automated Tests**', '- [x] 🧪 **Automated Tests**')
            
            print(body)
            ")
            echo "$NEW_BODY" > final_body.md
            gh pr edit "$PR_NUMBER" --body-file final_body.md
          else
            echo "Anchor not found, appending to description..."
            { echo "$CURRENT_BODY"; echo ""; echo "## 🚦 Test Results"; echo ""; cat test_summary.md; } > final_body.md
            
            # Attempt to check box via sedan substitution if appending
            if [ -f test_outcome.txt ] && grep -q "SUCCESS" test_outcome.txt; then
               sed -i 's/- \[ \] 🧪 \*\*Automated Tests\*\*/- [x] 🧪 **Automated Tests**/' final_body.md
            fi
            
            gh pr edit "$PR_NUMBER" --body-file final_body.md
          fi
        else
          echo "Posting as a PR comment..."
          COMMENT_ID=$(gh pr view "$PR_NUMBER" --json comments --template '{{range .comments}}{{if contains .body "🚦 Test Suite Results"}}{{.id}}{{"\n"}}{{end}}{{end}}' | head -n 1)
          
          if [ -n "$COMMENT_ID" ]; then
            gh pr comment "$PR_NUMBER" --edit-id "$COMMENT_ID" --body-file test_summary.md
          else
            gh pr comment "$PR_NUMBER" --body-file test_summary.md
          fi
        fi
