name: 'Run QA Test Suite'
description: '🧪 Core engine for executing API, GUI, and Performance tests with service orchestration and health checks.'
branding:
  icon: 'play-circle'
  color: 'green'
inputs:
  start-services-command:
    description: 'Command to start background services (e.g., npm start &)'
    required: false
    default: ''
  health-check-urls:
    description: 'Space-separated URLs to wait for (e.g., http://localhost:3000)'
    required: false
    default: ''
  test-command-api:
    description: 'Command for API tests (e.g., npm run test:api)'
    required: false
    default: ''
  test-command-performance:
    description: 'Command for Performance tests (e.g., locust -f locustfile.py)'
    required: false
    default: ''
  test-command-gui:
    description: 'Command for GUI tests (e.g., npm run test:gui)'
    required: false
    default: ''
  run-api:
    description: 'Whether to run API tests'
    required: false
    default: 'true'
  run-performance:
    description: 'Whether to run performance tests'
    required: false
    default: 'true'
  run-gui:
    description: 'Whether to run GUI tests'
    required: false
    default: 'true'
  headless:
    description: 'Run GUI tests in headless mode'
    required: false
    default: 'true'
  enable-coverage:
    description: 'Whether to collect code coverage'
    required: false
    default: 'false'
  coverage-module:
    description: 'Module to collect coverage for'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run API Tests
      if: inputs.run-api == 'true' && inputs.test-command-api != ''
      shell: pwsh
      run: |
        if ("${{ inputs.enable-coverage }}" -eq "true" -and "${{ inputs.coverage-module }}" -ne "") {
          pytest --cov=${{ inputs.coverage-module }} tests/ --cov-report=xml
        } else {
          ${{ inputs.test-command-api }}
        }
        # Standardize report stashing for this infrastructure
        if (Test-Path "reports") {
          cp -r reports api_reports_tmp
          rm -rf reports/test_run
        }

    - name: Run Performance Tests
      if: inputs.run-performance == 'true' && inputs.test-command-performance != ''
      shell: pwsh
      run: |
        ${{ inputs.test-command-performance }}

    - name: Run GUI Tests
      if: inputs.run-gui == 'true' && inputs.test-command-gui != ''
      shell: pwsh
      run: |
        ${{ inputs.test-command-gui }}
      env:
        HEADLESS: ${{ inputs.headless }}
